"""added fullname to queue_member

Revision ID: 447ac308202a
Revises: 67f039998856
Create Date: 2021-01-10 01:19:11.568824

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '447ac308202a'
down_revision = '67f039998856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_member', sa.Column('fullname', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_member', 'fullname')
    # ### end Alembic commands ###
