"""message id to edit

Revision ID: 464c253e9a8a
Revises: f7ecbcd2adf4
Create Date: 2021-01-09 23:47:52.454685

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '464c253e9a8a'
down_revision = 'f7ecbcd2adf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('message_id_to_edit', sa.Integer()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue', 'message_id_to_edit')
    # ### end Alembic commands ###
