"""changed chat_id and user_id to BigInteger

Revision ID: 5b5020e5884d
Revises: 447ac308202a
Create Date: 2021-01-12 00:41:22.998074

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '5b5020e5884d'
down_revision = '447ac308202a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('alter table chat alter column chat_id type bigint using chat_id::bigint;')
    op.execute('alter table queue alter column chat_id type bigint using chat_id::bigint;')
    op.execute('alter table queue_member alter column user_id type bigint using user_id::bigint;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('alter table chat alter column chat_id type integer using chat_id::integer;')
    op.execute('alter table queue alter column chat_id type integer using chat_id::integer;')
    op.execute('alter table queue_member alter column user_id type integer using user_id::integer;')
    # ### end Alembic commands ###
