"""moved current_order to queue

Revision ID: 67f039998856
Revises: c512e91ab277
Create Date: 2021-01-10 00:39:38.640430

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from sqlalchemy import text


revision = '67f039998856'
down_revision = 'c512e91ab277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('current_order', sa.Integer(), nullable=False, server_default=text('0')))
    op.drop_column('queue_member', 'current_order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_member', sa.Column('current_order', sa.Integer(), nullable=False, server_default=text('0')))
    op.drop_column('queue', 'current_order')
    # ### end Alembic commands ###
