"""moved motify from queue to chat

Revision ID: 6ec0df337820
Revises: b1c5140ae520
Create Date: 2021-01-12 22:46:40.351768

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from sqlalchemy import text


revision = '6ec0df337820'
down_revision = 'b1c5140ae520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('notify', sa.BOOLEAN(), nullable=False, server_default=text('true')))
    op.drop_column('queue', 'notify')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('notify', sa.BOOLEAN(), nullable=False, server_default=text('true')))
    op.drop_column('chat', 'notify')
    # ### end Alembic commands ###
