"""changed the behavior of chat_id in Queue to CASCADE

Revision ID: b1c5140ae520
Revises: 5b5020e5884d
Create Date: 2021-01-12 21:29:18.143670

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'b1c5140ae520'
down_revision = '5b5020e5884d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('queue_chat_id_fkey', 'queue', type_='foreignkey')
    op.create_foreign_key(None, 'queue', 'chat', ['chat_id'], ['chat_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queue', type_='foreignkey')
    op.create_foreign_key('queue_chat_id_fkey', 'queue', 'chat', ['chat_id'], ['chat_id'])
    # ### end Alembic commands ###
