"""renamed to queue_membeR

Revision ID: c512e91ab277
Revises: 464c253e9a8a
Create Date: 2021-01-10 00:15:59.522887

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'c512e91ab277'
down_revision = '464c253e9a8a'
branch_labels = None
depends_on = None


# noinspection SqlResolve
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('queue_members', 'queue_member')
    op.execute('ALTER TABLE queue_member RENAME CONSTRAINT queue_members_pkey to queue_member_pkey;')
    op.execute('ALTER TABLE queue_member RENAME CONSTRAINT queue_members_queue_id_fkey TO queue_member_queue_id_fkey')
    # op.execute('ALTER INDEX queue_members_pkey RENAME TO queue_member_pkey')
    # ### end Alembic commands ###


# noinspection SqlResolve
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('queue_member', 'queue_members')
    op.execute('ALTER TABLE queue_member RENAME CONSTRAINT queue_member_pkey to queue_members_pkey;')
    op.execute('ALTER TABLE queue_member RENAME CONSTRAINT queue_member_queue_id_fkey TO queue_members_queue_id_fkey')
    # op.execute('ALTER INDEX queue_member_pkey RENAME TO queue_members_pkey')
    # ### end Alembic commands ###
