"""added language setting to chat entity

Revision ID: da6ffa3dbf14
Revises: 6ec0df337820
Create Date: 2021-05-13 20:37:37.620167

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from sqlalchemy import text


revision = 'da6ffa3dbf14'
down_revision = '6ec0df337820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('language', sa.String(), nullable=False, server_default=text("'en'")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'language')
    # ### end Alembic commands ###
