"""Added silent_mode attr to chat

Revision ID: dcc73a102df6
Revises: 6ec0df337820
Create Date: 2021-06-01 13:27:36.683928

"""
import sqlalchemy as sa
from alembic import op
# revision identifiers, used by Alembic.
from sqlalchemy import text


revision = 'dcc73a102df6'
down_revision = '6ec0df337820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('silent_mode', sa.BOOLEAN(), nullable=False, server_default=text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'silent_mode')
    # ### end Alembic commands ###
