"""added foreign key for chat_id to queue

Revision ID: f7ecbcd2adf4
Revises: bae3d4951627
Create Date: 2021-01-08 15:46:20.400112

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'f7ecbcd2adf4'
down_revision = 'bae3d4951627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chat', ['chat_id'])
    op.add_column('queue', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'queue', ['queue_id'])
    op.create_foreign_key(None, 'queue', 'chat', ['chat_id'], ['chat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queue', type_='foreignkey')
    op.drop_constraint(None, 'queue', type_='unique')
    op.drop_column('queue', 'chat_id')
    op.drop_constraint(None, 'chat', type_='unique')
    # ### end Alembic commands ###
